### ISSUE TITLE
Bad pointing

### ISSUE THREAD

**Issue by JunCTionS** [GLORIA-project/solar-experiment-interface#2]
Today while testing the system I could not point it to the Sun. Clicking on the Sun icon it would point nearby but not enough for it to be seen in the finder
![black](https://f.cloud.github.com/assets/4676704/2049413/ed3a180a-8a5f-11e3-863d-84e9261ba71c.png)
Then trying to use the finder's arrow clicking several times up, and then clicking the Sun icon again it would point somewhere obviously wrong, like to the ground **note the telescope image on the lower left**:
![pointingdown](https://f.cloud.github.com/assets/4676704/2049414/ed9a006c-8a5f-11e3-9a89-f1e3c3144272.png)
or to the dome:
![pointingnowhere](https://f.cloud.github.com/assets/4676704/2049415/ed9c9c28-8a5f-11e3-910c-f44985ef490b.png)

This was done at January 31st around 10:00 UT

**Comment by fserena** [comment]
This happens sometimes when the telescope loses the pointing. Telescope owners should do regular maintenance. Now this problem is solved.

**Comment by JunCTionS** [comment]
So it won't happen again or should this problem be fixed locally and not in software?

It happened intermittently while I was observing, would that be consistent with what you mention? 

My experience of not getting any error feedback gave me an impression of unreliability.
