### ISSUE TITLE
The system expells the user during an observation after GLORIA interface hung while taking a second image of the sun

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/solar-experiment-interface#23]
The system expells the user during an observation after alGLORIA interface hung while taking a second image of the sun

The problem is that after having taken one image of the sun, the user tried to take another image and then the system hung. So the user refreshed the website and then appeared a error screen.

Afterwards, the user tried to access from the reservations menu but GLORIA interface expelled the user and the next time the user tried to enter GLORIA, it showed the message: 'USUARIO NO VALIDO'.

It happend with Firefox.

**Comment by fserena** [comment]
This issue refers to a situation where GLORIA developers were doing some maintenance tasks. I'll keep this closed until it happens again (hopefully not) and a new comment is pushed  here with more details e.g. screenshots.

**Comment by angelagonzalez** [comment]
In fact I have a video of 11 minutes that shows all, what it is enough to prove that the problem exists.
