### ISSUE TITLE
There are some artifacts on the sun images

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/solar-experiment-interface#24]
There are some artifacts on the sun images

I append an image that shows it.

![artefactos tad solar 24-04-2014](https://cloud.githubusercontent.com/assets/6812954/2789760/704b96a4-cbb2-11e3-8d49-e37ae4dd77d0.jpg)

**Comment by mserraricart** [comment]
Thanks Angela. 
As you probably know this is a flat problem because the sun image is a raw one.
Maybe in the future we can try to develop automatic scripts to show reduced images but 
now this has not priority.

**Comment by angelagonzalez** [comment]
Ok, thanks for the information.
