### ISSUE TITLE
The button for pointing to the sun leades the telescope farer than in the begining

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/solar-experiment-interface#25]
The button for pointing to the sun leades the telescope farer than in the begining

When the user clicks on the button of the sun -which it is supposed to center the sun images- the sun disappears from the main telescope field of view, and it is more difficult to center it than before clicking on the sun icon.

**Comment by mserraricart** [comment]
This is also a mapping problem related with telescope mounting not software issues. 
In any case we have a wide field camera in order to correct pointing errors.
