### ISSUE TITLE
The sun did not appear in the main telescope on 24th April 2014 at 17:30 UT and other incidences

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/solar-experiment-interface#26]
The sun did not appear in the main telescope on 24th April 2014 at 15:30 UT

Firslyt, I entered my reservation and the only images displayed were the outside and inside webcams. The only thing shown by the main and the finder telescope was noise, during 5 minutes or more.

Secondly, the sun appeard in the finder telescope but not in the main one, whose image remained black until the end of the observation.

Thirdly, I logged out and in in order to access to my reservation again.

This time the controls of open/close the dome did not work properly.

In addition, when the dome was closed, the image of the sun appeared in the finder telescope, what was impossible since the dome was closed.

Finally, no control of the solar GUI worked properly.

**Comment by fserena** [comment]
This seems to be that your test were in sync with one of the many yersterday's deployments we did. To get a more reliable result, please do ensure that no developer is doing maintenance when you are about to start testing.
