### ISSUE TITLE
It is not possible to return to the observation after taking an image

### ISSUE THREAD

**Issue by angelagonzalez** [GLORIA-project/solar-experiment-interface#27]
Test Date: 26th April 2014 15:30 UT
Web browser: Firefox

After the user saves an image during an observation, it is not possible to go back to it, neither by clicking outside the taken image, nor by clicking on the back arrow of the web browser (in this last case, the user must access the observation again).

The only way to return to the observation without going out of it, is to refresh the web browser, but the user does not know it.

Suggestion: to include a button of 'Back to the Observation', in order the user not to miss time figuring out how to do it.

![to include a back button](https://cloud.githubusercontent.com/assets/6812954/2809332/9e32ac5e-cd67-11e3-8ef8-11737f2b6272.jpg)

**Comment by fserena** [comment]
Let's test it tomorrow with Firefox.

Please, summarize as much as possible issue titles to get a better understanding of each of them. They should be a tip of the incidence, like an identifier, not a story. 

Thanks.

**Comment by angelagonzalez** [comment]
The point here is to solve the issue, not to tell a story talking about telling stories.

**Comment by mserraricart** [comment]
I have a similar problem (using CROME in MAC-OS) but if I push in the botton of the images it works. I agree with Angela that it will be useful to include an additional button for returning to the interface.
