### ISSUE TITLE
Inconsistent North/South East/West directions

### ISSUE THREAD

**Issue by JunCTionS** [GLORIA-project/solar-experiment-interface#3]
When using the finder, if one presses the move North or South the Sun moves Up or Down respectively in the image, however when one presses East or West (right or left) it moves Left or Right respectively.

This is probably very counter-intuitive to normal users. I think the behaviour should be like that of the Up/Down (move the Sun in that direction within the image), but in any case it should at least be consistent.

**Comment by fserena** [comment]
I'm told this is not a trivial issue. But I agree this can confuse users. The telescope owner should answer here :)
