### ISSUE TITLE
Unresponsive focuser and exposure sliders

### ISSUE THREAD

**Issue by JunCTionS** [GLORIA-project/solar-experiment-interface#4]
Changing the positions on both the focuser and exposure sliders has no effect on the image, for example:

![nochange](https://f.cloud.github.com/assets/4676704/2049807/6a6594f6-8a67-11e3-9cfa-e721b1dee1ab.png)

I believe focus is not optimal.
![after](https://f.cloud.github.com/assets/4676704/2049819/a7dc5612-8a67-11e3-880e-40a0e526b695.jpg)

**Comment by fserena** [comment]
You need to click the button (you called it "slider") after you've prepared the corresponding value on both cases. Thank you.

**Comment by JunCTionS** [comment]
What button? The plus or minus signs? I clicked those to get the slider all the way to the bottom to try an extreme position as is shown in the first image. 

Or do you mean the box icon which changes position with this? this seems very counterintuitive. I wasn't able to reproduce right now as the page doesn't finish loading. I wouldn't call this issue closed yet...

**Comment by JunCTionS** [comment]
ah, yesterday while seeing some students try the systems out I understood what you meant, and I see it was indeed the icon. 

However I failed to see it from your answer because the focus doesn't respond immediately, in fact, we managed to defocus the image but never to focus it again du to the lack of a clear response.
