### ISSUE TITLE
Improve live Telescope Information

### ISSUE THREAD

**Issue by mserraricart** [GLORIA-project/solar-experiment-interface#5]
Add Telescope on-site information in the Make Reservation page.
The information could be: Observatory live image / humidity / wind velocity
In the case of the TAD the live image can be

http://meteo.ot-admin.net/webcam/ot-west.jpg

**Comment by fserena** [comment]
This issue is related to the Reservations repository: https://github.com/GLORIA-project/Reservations/issues/3
