### ISSUE TITLE
telescope pointing

### ISSUE THREAD

**Issue by mserraricart** [GLORIA-project/solar-experiment-interface#7]
We have detected a BUG in the telescope pointing function.
If you directly push goto the Sun button the dome is opened and the telescope points to the Sun.
But if you first open the open (with buttons included in the dome image) the dome is opened but if you try to point the telescope does not work.

**Comment by fserena** [comment]
It seems that there is a problem with the "point-to-object" experiment operation while trying to open the dome. By now, the execution of this operation will only point the telescope to the specified object, so the dome opening will dissapear.
